### ISSUE TITLE
An error on map load

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/better-movement-v2#1]
[Better Movement V2] lua/autorun/!!!!!sh_bm_main.lua:631: attempt to perform arithmetic on field 'm_flStepSoundTime' (a nil value)
    1. v - lua/autorun/!!!!!sh_bm_main.lua:631
        2. unknown - lua/includes/modules/hook.lua:96

That's pretty much all the info, quite literally

**Comment by relaxtakenotes** [comment]
ur fast on this... will fix

**Comment by relaxtakenotes** [comment]
should be fixed
