### ISSUE TITLE
[bug] better movement v2 incompatibility with viewpunch viewbob after march update

### ISSUE THREAD

**Issue by xxyy-me** [relaxtakenotes/better-movement-v2#12]
March update arrived.
And now Viewpunch Viewbob doesn't work for any kind of movement when using Better Movement V2. Camera doesn't shake when walking, running and so on. Also, the camera tilt seems to be broken too.

> Better Movement (original one) works just fine. Could use it, but I like the new version better.

---
gmod build 13727688 / x64 branch, only addons installed _Better Movement V2_, _Local Viewpunch_, _Viewpunch Viewbob_

**Comment by xxyy-me** [comment]
Still not working.

**Comment by relaxtakenotes** [comment]
still working for me.
