### ISSUE TITLE
Unable to move after landing with landing slowdown turned off

### ISSUE THREAD

**Issue by lilm0nsterdemon** [relaxtakenotes/better-movement-v2#13]
All the other slowdown toggles work fine but turning off slowdown On Landing just makes you unable to move.

video for proof
https://github.com/relaxtakenotes/better-movement-v2/assets/161146595/efa75c28-8695-404a-81c0-8c027b7fbe00

**Comment by relaxtakenotes** [comment]
yea settings r busted as fudge. i might get around to fixing those, but not sure

**Comment by relaxtakenotes** [comment]
fixed (yay)
