### ISSUE TITLE
incorrect viewmodel animation

### ISSUE THREAD

**Issue by narniaaaa** [relaxtakenotes/better-movement-v2#16]
The problem appears with modern warfare base weapons. its demonstrated in this video https://youtu.be/Ql8YOp2ACx8
speed:
run 100
walk 90
slow walk 85

**Comment by relaxtakenotes** [comment]
due to the way my mod works and the way that mwb calculates move states i am unable to do anything other than patch their code to work with mine. will i do that? most likely not

**Comment by narniaaaa** [comment]
> due to the way my mod works and the way that mwb calculates move states i am unable to do anything other than patch their code to work with mine. will i do that? most likely not

okay,thank you for answering me!
