### ISSUE TITLE
Analog directional movement

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/better-movement-v2#2]
I guess I already know you probably won't care enough for this, but could you possibly implement directional analog movement for controllers? It's present in the original game's movement, it works in TacMove, not in BM&BM2 though
Not asking for analog movement as a whole (although that would've been sick), just the directional movement..

**Comment by relaxtakenotes** [comment]
i never even got a gamepad working with the game so idk :\
maybe tho

**Comment by Lombaxtard** [comment]
> i never even got a gamepad working with the game so idk : maybe tho

Got only movement (not the camera) working, only needs "joystick 1" and "joystick_force_disabled 0"

**Comment by relaxtakenotes** [comment]
well i used these commands and everything seems to work fine? not sure what u mean https://staging.streamable.com/2bj8w3

**Comment by Lombaxtard** [comment]
A crude demonstration here (watch your eyes!). Lines represent directions relative to the center, directions you can take with inputs

Here's what BM's movement is like (basically the same way as a regular keyboard) - digital:
![IMG_20231124_230500](https://github.com/relaxtakenotes/better-movement-v2/assets/75931669/bc367078-fa45-4300-948a-2372287fcc8d)

Here's what default GMod, TacMove movement is like - analog:
![IMG_20231124_230410](https://github.com/relaxtakenotes/better-movement-v2/assets/75931669/8b04dd6f-ab6a-4ba5-a861-c41a7b2a057a)

Then there's movement speed that would depend on how far you push a stick in any direction (from low(centered), to max speed not sprinting(edge)), but that's not something native to Garry's Mod, unlike Half-Life 2. So this one is just another cool wish and that'd also be a first addon of that kind

**Comment by relaxtakenotes** [comment]
sorry for being a bit nonunderstanding here but do the example images apply to the gamepad? i felt like the movement was pretty much analog

**Comment by relaxtakenotes** [comment]
fix pushed

**Comment by Lombaxtard** [comment]
> fix pushed

Wow, you've actually not only fixed directional movement, but also added analog movement speed as well! This feels great, it really is a first in Garry's Mod's history, congratulations and many thanks to you
P.S. If you ever desire to use controller in GMod, be sure to set dead zone type to "square" in SteamInput or whatever you prefer (trust me). Also beware that many addons for some reason only recognize left analog up and down for movement (DRGBase possessor for example, not to mention many vehicle mods such as LFS, LVS, and simfphys since not so long ago analog support was removed)
