### ISSUE TITLE
An error I found.

### ISSUE THREAD

**Issue by sigarett** [relaxtakenotes/better-movement-v2#3]
[Better Movement V2] lua/autorun/!!!!!sh_bm_main.lua:553: attempt to perform arithmetic on field 'iSkipStep' (a nil value)
  1. UpdateStepSound - lua/autorun/!!!!!sh_bm_main.lua:553
   2. fn - lua/autorun/!!!!!sh_bm_main.lua:614
    3. unknown - lua/ulib/shared/hook.lua:109
    

Seems to be something with one of my other mods, but was wondering if it would be possible to find way around it instead of removing one mod or the other?

**Comment by relaxtakenotes** [comment]
this shouldn't cause errors no matter the mods, so that'll be fixed

**Comment by relaxtakenotes** [comment]
fix pushed
