### ISSUE TITLE
Stepsound request

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/better-movement-v2#4]
I thing I've mentioned this a long time ago, but is it possible that you'd implement a different formula for stepsoundtime?
There would be slowwalk, walk, and run definable variables (in ticks or ms, whatever it is now) that would determine stepsound delay (just like Simple Player Speed Changer has it now), then that value would be contracted by current movement speed percentage inverted (movtype - movspeedinv = stepsoundtime) or something like that. Apologies for a hasty explanation..

So if every move type has it's own stepsoundtime value, then let's say, walk move type has it at 400 at 100% walk speed (not transitioning), which would then transition into run move type's value of 200, gradually, being at 300 ticks when movement speed is 50% into transition in between walk and run movement speed.
I said it once, and I'll say it again - being able to sync stepsoundtime exactly to the way your character moves it's legs is another level of feast for your eyes and ears. I think the implementation is something like duplicating movement speed acceleration and deceleration to instead feature stepsoundtime.

Perhaps even add an offset for every third step (L4D Reanimation has assymetrical animation loop just like in the game, which approximately means: step > 151ticks > step > 160 ticks > step > 151 ticks > and so on)

Anyway, separate stepsoundtime values would be enough of a bliss, I'm just daydreaming here in regards to third step offset, if you're up for this of course

**Comment by relaxtakenotes** [comment]
syncing footsteps with the playermodel using numbers is pretty stupid and is just a waste of time. i am planning on adding some sort of a feature that emits footsteps when the actual leg hits something, but god knows when i'll get it right.
there's an implementation of it here: https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/essential/autorun/realistic_footsteps.lua, but due to the license and the fact that i just plain out don't like it, i'm pretty hesitant on using it.

**Comment by Lombaxtard** [comment]
> syncing footsteps with the playermodel using numbers is pretty stupid and is just a waste of time. i am planning on adding some sort of a feature that emits footsteps when the actual leg hits something, but god knows when i'll get it right. there's an implementation of it here: https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/essential/autorun/realistic_footsteps.lua, but due to the license and the fact that i just plain out don't like it, i'm pretty hesitant on using it.

I agree. I wish there was an alternative, but there just isn't, so it's the only thing left for me to do and synced leggy sounds are just so gr8 to experience
And I don't suppose GMod's animation system is similar to TF2 or Left 4 Dead 2 to imitate this: https://steamcommunity.com/sharedfiles/filedetails/?id=2939300103

**Comment by relaxtakenotes** [comment]
i'll have to see. maybe there's a hidden event that fires on footstep...

**Comment by relaxtakenotes** [comment]
nope, there isn't. hacky trace checks it is then lol

**Comment by Lombaxtard** [comment]
> nope, there isn't. hacky trace checks it is then lol

Bloody garry, why did you stop at ep2 engine...

**Comment by relaxtakenotes** [comment]
https://staging.streamable.com/erkywx
wasnt too hard to implement, did it in about 10 minutes cause i already had most of the footstep shit done, just needed to do the traces. still need to iron out a few issues tho

**Comment by Lombaxtard** [comment]
> https://staging.streamable.com/erkywx wasnt too hard to implement, did it in about 10 minutes cause i already had most of the footstep shit done, just needed to do the traces. still need to iron out a few issues tho

Jeez, good stuff! Can't wait to try it out when you're done (I'm just wondering how well it will play with some of the reanimations out there)
How expensive is it btw? A bit curious and a little concerned .-.

**Comment by relaxtakenotes** [comment]
caused by non forward slowdown most likely

**Comment by relaxtakenotes** [comment]
i pushed some improvements to the anim based footsteps and a different mode that should work just a bit better.
CreateConVar("sv_bm_animevent_footsteps_type", 0, flags, "0 - regular traces, 1 - util.IsOBBIntersectingOBB"),
CreateConVar("sv_bm_animevent_footsteps_offset", 8, flags, "Foot offset if the type is 1"),

**Comment by Lombaxtard** [comment]
Type 1 works wonders on slopes (instead of 4-6 footstep sounds per second there is correct amount now in accordance to leg movements

Btw, what is <a href="https://staging.streamable.com/vwnn4g">this</a> about? An undefined material? Type 0 and 1 doesn't work on it regardless (it was an issue before this last update, it's just that I finally got to documenting it
Map is <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1765064201">Pripyat Remaster</a>

**Comment by relaxtakenotes** [comment]
i suppose so, will see

**Comment by relaxtakenotes** [comment]
fixed. the trace for some reason didn't return the surface properties id on that specific surface

**Comment by Lombaxtard** [comment]
> fixed. the trace for some reason didn't return the surface properties id on that specific surface
Gorgeous, thank you good sir



Also...
> P.S.2 So you're not gonna bring back separate ladder speed multiplier from SPSC?...
> 
> P.S.3 ...and "force_speed" to override weapons...

**Comment by relaxtakenotes** [comment]
i forgot i had those features...

**Comment by relaxtakenotes** [comment]
readded them :-)

**Comment by Lombaxtard** [comment]
Wondrous news, it's so good to have them back :3
Btw, how does "sv_bm_animevent_footsteps_offset" work? I tried changing it's value, but I can't see any difference (also, if I lower/increase it by more than 1 then footstep sounds stop emitting completely). And yes, "type" is set to 1

**Comment by relaxtakenotes** [comment]
just offsets ur foot by the z axis. positive numbers offset it down, negative offset it up

**Comment by Lombaxtard** [comment]
Just found out footsteps are clientside-only (other players walk silently)

**Comment by relaxtakenotes** [comment]
that's not clientside only? even so, it's more realistic, because you can't hear footsteps from a mile away

**Comment by Lombaxtard** [comment]
No, I mean completely silent, as in I can't hear myself walking if I'm using the Camera tool or even if I create a bot and make him move. I haven't tested without animevent footsteps, but it should probably work fine as in your addon's page video (I'm using your edit of the original PF HL Alyx btw)

**Comment by relaxtakenotes** [comment]
... bots are bots, and the issue regarding your footsteps not being played is probably because of setupbones not being called, which i fixed before you replied.
regardless, everything works for me after the setupbones change https://staging.streamable.com/gpcr21

**Comment by Lombaxtard** [comment]
> ... bots are bots, and the issue regarding your footsteps not being played is probably because of setupbones not being called, which i fixed before you replied. regardless, everything works for me after the setupbones change https://staging.streamable.com/gpcr21

Okay, it probably should've worked for me before, but anyway... Here's the actual problem:
Default footsteps with only CTV and BM2 installed, and I hear footsteps when looking through the camera. But when I add your edit of PF HL Alyx footsteps disappear the moment I switch to camera and return when I switch back off it
I just didn't test with no addons but the target ones enabled before, so here you go

P.S. A question if I may: do DSteps work properly with Viewpunch Viewbob unlike Presence Footsteps? I like PF HL Alyx a lot but they get old. And I got kinda disappointed that your edit was not of the most feature rich version of PF so I wasn't able to properly port one of my favorites to it. I'm also lazy :p and on the lookout for ready-to-use solutions of compatible footsteps (default PF addons emit both native Garry's Mod footsteps and PF at the same time using BM2 with animevent)

**Comment by relaxtakenotes** [comment]
1) doesnt sound like the issue i'll be fixing.
2) yeah. i nabbed its fix for footsteps for my pf alyx edit

**Comment by Lombaxtard** [comment]
> 1. doesnt sound like the issue i'll be fixing.
> 
>     2. yeah. i nabbed its fix for footsteps for my pf alyx edit

Thanks for the reply
Btw, I just tested animevent with DSteps and this combo makes footsteps work regardless, always. Just like vanilla incremental footsteps already do
Might be something of use to you should you consider otherwise...

**Comment by Lombaxtard** [comment]
I hope you're okay if I dump this batch here...

1. After getting the latest update (or maybe it was one update before that) <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2922252697">wounded limping</a> stopped working as intended. Specifically it does not slowdown you when you're limping anymore (sv_bm_remove_weapon_hooks 0).

2. If I jump onto something low enough without making a landing sound (regardless of animevent footsteps. I think it's related to what you've been describing of landing footstep sound) I won't make any footstep sounds until I jump AND get a landing sound from it.

3. Another thing I've been meaning to report was that with "sv_bm_slowdown_on_landing" set to 0 movement is completely locked until I turn it back on. Not sure what's that about, I'm also pretty sure this was present on release, but I didn't seem to make much of it..

**Comment by Lombaxtard** [comment]
Oh, and a very strange fucked-up thing coming up
Using <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2922279661">Extended Player Animations</a> and the newest BM2 version slows you down when you switch to an ar2/smg/shotgun/rpg holdtype..? Wtf, I just tested with exact same set of addons except for using an older BM2 version and it didn't slow me down with it. It didn't with the newest one...

**Comment by relaxtakenotes** [comment]
![VSCodium_WRQLzGPJF1](https://github.com/relaxtakenotes/better-movement-v2/assets/91839650/1dcf90e2-912a-43a9-866f-7c4d01e38dc6)
![VSCodium_D0yD1lRz9K](https://github.com/relaxtakenotes/better-movement-v2/assets/91839650/fca4c094-c6c1-4f23-9edc-1e1f10dd8983)
these are the only places where something at all can happen to break my shit, but i think not even these are the real culprits. idk why it happens, only guess is that either the forward/side move are getting fucked or maxspeed.

**Comment by Lombaxtard** [comment]
Oh my god, nevermind the second message, I just got struck by how idiotic this particular slowdown was being achieved
Turnded out it was TacRP's fault of slowing the player down. Do you know why? When you use weapon selector and press LMB to confirm, TacRP already assumes you are in the process of firing a weapon and slows you down in accordance to it's mechanics. I've no idea how I've missed it, I tested two different versions of BM2 in good faith and results were consistent with what I've stated in the previous message, but now that I've tested again it finally occurred to me what it was and slowdown actually started happening with an older BM2 as well. Somehow my mouse presses have changed and became shorter or wtf..?
