### ISSUE TITLE
Unable to move after setting "sv_bm_turn_slowdown" to "0" and restarting map.

### ISSUE THREAD

**Issue by ScottVordem** [relaxtakenotes/better-movement-v2#6]
This is the exact situation as #5 I posted except I actually found the cause...at least I hope I did.

When I set "sv_bm_turn_slowdown" to "0" and restart the map (or load a new one), movement is completely broken. I can't move or jump except in noclip and disable the addon via "sv_bm_enabled" makes me take off  like a rocket at the speed of sound.

Changing "sv_bm_turn_slowdown" back to "1" and restarting puts things back to normal, I don't think this is how it's supposed to work.

Just a reminder that I don't have any other addons that modify player movement.

I'm in x64 branch still.

**Comment by relaxtakenotes** [comment]
fixed. will push later
