### ISSUE TITLE
CONFLICTING MOD: datæ's "Simple Leaning"

### ISSUE THREAD

**Issue by Dudebro20001** [relaxtakenotes/better-movement-v2#7]
The better movement mod makes it so you lean very, very slow. Ples fix, i love the better movement mods and im heartbroken that i cant use the new one :(

**Comment by relaxtakenotes** [comment]
actually no, i'll keep this open but add the label wontfix so that people can see what mods are incompatible.

**Comment by relaxtakenotes** [comment]
added an option that breaks other mod features such as controller support. might break other mods in other ways but pick your poison. will push later.
