### ISSUE TITLE
CONFLICTING MOD: datæ's "Simple Knockback"

### ISSUE THREAD

**Issue by ManiaSonicRUS** [relaxtakenotes/better-movement-v2#8]
I use some hella small old knockback (for explosions and antlion guards) addon by datae that was included with hella old leaked vmanip versions (I modified it a bit so it works without vmanip as I really love such a small touch as knockback), and yup bmv2 locks the movement when player is knockbacked. I can toggle noclip to get movement working again tho, but it reduces jump height alot like its not possible to jump at all.
The bmv1 suffered from the same problem some time ago; then it started working later somehow so plz try to fix it again as it works with bmv1.
I uploaded the knockback lua as txt (github doesn't accept lua)
[sv_vmanipknockback.txt](https://github.com/relaxtakenotes/better-movement-v2/files/13533500/sv_vmanipknockback.txt)
If there was any other knockback addon I'd use it surely, but seems no one is interested in making such.

**Comment by relaxtakenotes** [comment]
actually no, i'll keep this open but add the label wontfix so that people can see what mods are incompatible.

**Comment by ManiaSonicRUS** [comment]
Жалко, ладно
Пришлось на bmv1 откатиться, всё равно со старой версией играется как-то подобрее и поаркаднее

**Comment by relaxtakenotes** [comment]
added an option that breaks other mod features such as controller support. might break other mods in other ways but pick your poison. will push later.

**Comment by Lombaxtard** [comment]
> I use some hella small old knockback (for explosions and antlion guards) addon by datae that was included with hella old leaked vmanip versions (I modified it a bit so it works without vmanip as I really love such a small touch as knockback), and yup bmv2 locks the movement when player is knockbacked. I can toggle noclip to get movement working again tho, but it reduces jump height alot like its not possible to jump at all. The bmv1 suffered from the same problem some time ago; then it started working later somehow so plz try to fix it again as it works with bmv1. I uploaded the knockback lua as txt (github doesn't accept lua) [sv_vmanipknockback.txt](https://github.com/relaxtakenotes/better-movement-v2/files/13533500/sv_vmanipknockback.txt) If there was any other knockback addon I'd use it surely, but seems no one is interested in making such.

It actually does work for me, but I managed to break SK with an addon conflict and restore SK's functionality by solving said conflict (unless it doesn't work for you with just the BM2 and Simple Knockback installed anyway), I was using BM2 version from 28th of November btw

**Comment by ManiaSonicRUS** [comment]
> > I use some hella small old knockback (for explosions and antlion guards) addon by datae that was included with hella old leaked vmanip versions (I modified it a bit so it works without vmanip as I really love such a small touch as knockback), and yup bmv2 locks the movement when player is knockbacked. I can toggle noclip to get movement working again tho, but it reduces jump height alot like its not possible to jump at all. The bmv1 suffered from the same problem some time ago; then it started working later somehow so plz try to fix it again as it works with bmv1. I uploaded the knockback lua as txt (github doesn't accept lua) [sv_vmanipknockback.txt](https://github.com/relaxtakenotes/better-movement-v2/files/13533500/sv_vmanipknockback.txt) If there was any other knockback addon I'd use it surely, but seems no one is interested in making such.
> 
> It actually does work for me, but I managed to break SK with an addon conflict and restore SK's functionality by solving said conflict (unless it doesn't work for you with just the BM2 and Simple Knockback installed anyway), I was using BM2 version from 28th of November btw

What addon conflict? I have 320 of addons, tell me the exact one that helped you then

**Comment by Lombaxtard** [comment]
> > > I use some hella small old knockback (for explosions and antlion guards) addon by datae that was included with hella old leaked vmanip versions (I modified it a bit so it works without vmanip as I really love such a small touch as knockback), and yup bmv2 locks the movement when player is knockbacked. I can toggle noclip to get movement working again tho, but it reduces jump height alot like its not possible to jump at all. The bmv1 suffered from the same problem some time ago; then it started working later somehow so plz try to fix it again as it works with bmv1. I uploaded the knockback lua as txt (github doesn't accept lua) [sv_vmanipknockback.txt](https://github.com/relaxtakenotes/better-movement-v2/files/13533500/sv_vmanipknockback.txt) If there was any other knockback addon I'd use it surely, but seems no one is interested in making such.
> > 
> > 
> > It actually does work for me, but I managed to break SK with an addon conflict and restore SK's functionality by solving said conflict (unless it doesn't work for you with just the BM2 and Simple Knockback installed anyway), I was using BM2 version from 28th of November btw
> 
> What addon conflict? I have 320 of addons, tell me the exact one that helped you then

I tested it on 2 modlists, each with about 200+ addons, both use BM2 though. On one SK worked, on another it didn't. So it's obviously a conflict you're gonna have to figure out. Just disable addons in sequental batches of 100 or 50 without sparing anything, then once you find the batch enable back a smaller number of addons from it, and so on. That is, if you really want it work
