### ISSUE TITLE
BM2's slowdown non forward on controller

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/better-movement-v2#9]
Prerequisite: "sv_bm_slowdown_non_forward_multiplier" set to "1".
There's an easy to reach consistently diagonal stick position that makes you barely move at all (like 5/7? units per second for me). I reckon it's the junction between "non-forward: backwards" and "non-forward: sideways" at which this issue occurs
I can record a snippet if you can't reproduce, otherwise would love to know if it's possible for you to fix this or not. Cheers

**Comment by relaxtakenotes** [comment]
i wouldn't use this feature on controllers

**Comment by relaxtakenotes** [comment]
fixed

**Comment by Lombaxtard** [comment]
There's no analog movement now...

**Comment by relaxtakenotes** [comment]
enable controller support

**Comment by Lombaxtard** [comment]
I think latest update caused this: https://staging.streamable.com/9n3k81
Moving exactly to the right or left (not the transition as before) specifically using a controller causes the afore demonstrated effect with ARC9 at least (seems like it doesn't count moving sideways with a stick as movement at all, as in BM1)
Important note: I thoroughly tested this issue under various conditions, such as disabled slowdown_non_forward, disabled controller support, tested the same movement with keyboard, attempted to force this behaviour by spamming A/D+W and A/D+S to get into this state, but it's only reproducible on a controller
I suppose if it's unfixable with some form of a new method, then it'd be totally OK to restore previous behaviour:

> There's an easy to reach consistently diagonal stick position that makes you barely move at all

And then it'd just be worth not using slowdown_non_forward in conjunction with a controller altogether

**Comment by Lombaxtard** [comment]
> im tired of all this... go try the newest version from the repo.

Unsuccessful

**Comment by relaxtakenotes** [comment]
unfortunate l0l
